# Generated by Django 3.2.6 on 2021-08-08 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField(default=18)),
                ('type_user', models.CharField(max_length=255)),
                ('mode_game', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
