# Generated by Django 3.2.5 on 2021-07-17 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('age', models.IntegerField(default=18, verbose_name='Age')),
                ('profession', models.CharField(blank=True, max_length=255, null=True, verbose_name='Profession')),
            ],
        ),
    ]
