# Generated by Django 3.2.6 on 2021-09-07 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210907_0827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='mode_game',
            field=models.CharField(choices=[('Mobile', 'Mobile'), ('Computer', 'Computer')], default='Mobile', max_length=50, verbose_name='Mode Game'),
        ),
    ]
